# Generated by Django 3.1 on 2020-08-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('000', 'Input'), ('001', 'Select'), ('010', 'Radio'), ('011', 'Checkbox'), ('100', 'Date'), ('101', 'Time'), ('110', 'Datetime'), ('111', 'Range')], default='000', max_length=3)),
                ('value', models.CharField(blank=True, max_length=1024, null=True)),
                ('data', models.ManyToManyField(to='core.Data')),
                ('sub_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_selectelement', to='core.subform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('000', 'Input'), ('001', 'Select'), ('010', 'Radio'), ('011', 'Checkbox'), ('100', 'Date'), ('101', 'Time'), ('110', 'Datetime'), ('111', 'Range')], default='000', max_length=3)),
                ('value', models.CharField(blank=True, max_length=1024, null=True)),
                ('sub_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_input', to='core.subform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.subform')),
            ],
        ),
        migrations.CreateModel(
            name='DateTimeElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('000', 'Input'), ('001', 'Select'), ('010', 'Radio'), ('011', 'Checkbox'), ('100', 'Date'), ('101', 'Time'), ('110', 'Datetime'), ('111', 'Range')], default='000', max_length=3)),
                ('value', models.DateTimeField(blank=True, null=True)),
                ('sub_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_datetimeelement', to='core.subform')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
