# Generated by Django 3.1 on 2020-08-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimeelement',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='input',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selectelement',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
