# Generated by Django 3.1 on 2020-08-08 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeElement',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.element')),
                ('value', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('core.element',),
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.element')),
                ('value', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            bases=('core.element',),
        ),
        migrations.CreateModel(
            name='SelectElement',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.element')),
                ('value', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            bases=('core.element', models.Model),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
                ('select_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.selectelement')),
            ],
        ),
    ]
