# Generated by Django 3.1 on 2020-08-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200809_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datetimeelement',
            name='type',
        ),
        migrations.RemoveField(
            model_name='input',
            name='type',
        ),
        migrations.RemoveField(
            model_name='selectelement',
            name='type',
        ),
    ]
