# Generated by Django 3.1 on 2020-08-09 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_datetimeelement_input_option_selectelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimeelement',
            name='sub_form',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='date_times', to='core.subform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input',
            name='sub_form',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='core.subform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectelement',
            name='sub_form',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='selects', to='core.subform'),
            preserve_default=False,
        ),
    ]
