# Generated by Django 3.1 on 2020-08-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200810_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='subform',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
