# Generated by Django 3.1 on 2020-08-11 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subform_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datetimeelement',
            name='sub_form',
        ),
        migrations.RemoveField(
            model_name='input',
            name='sub_form',
        ),
        migrations.RemoveField(
            model_name='selectelement',
            name='sub_form',
        ),
        migrations.AddField(
            model_name='datetimeelement',
            name='filed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='elements_datetimeelement', to='core.field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input',
            name='filed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='elements_input', to='core.field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectelement',
            name='filed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='elements_selectelement', to='core.field'),
            preserve_default=False,
        ),
    ]
