# Generated by Django 3.1 on 2020-08-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200811_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datetimeelement',
            old_name='filed',
            new_name='field',
        ),
        migrations.RenameField(
            model_name='input',
            old_name='filed',
            new_name='field',
        ),
        migrations.RenameField(
            model_name='selectelement',
            old_name='filed',
            new_name='field',
        ),
    ]
