# Generated by Django 3.1 on 2020-08-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200811_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('value', models.TimeField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_timeelement', to='core.field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RadioElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('value', models.CharField(blank=True, max_length=1024, null=True)),
                ('data', models.ManyToManyField(to='core.Data')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_radioelement', to='core.field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DateElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('value', models.DateField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_dateelement', to='core.field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckboxElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('value', models.CharField(blank=True, max_length=1024, null=True)),
                ('data', models.ManyToManyField(to='core.Data')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_checkboxelement', to='core.field')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
