# Generated by Django 3.1 on 2020-08-13 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200813_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='form',
            name='filler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='core.userprofile'),
        ),
    ]
