# Generated by Django 3.1 on 2020-08-13 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200813_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='subform',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_forms', to='core.form'),
            preserve_default=False,
        ),
    ]
