# Generated by Django 3.1 on 2020-08-13 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_subform_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='base_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='core.form'),
        ),
        migrations.AddField(
            model_name='form',
            name='is_template',
            field=models.BooleanField(default=True),
        ),
    ]
