# Generated by Django 3.1 on 2020-08-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200813_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='is_template',
        ),
    ]
