# Generated by Django 3.1 on 2020-08-13 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_form_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.userprofile'),
        ),
    ]
