# Generated by Django 3.1 on 2020-08-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200813_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='subform',
            name='is_grid',
            field=models.BooleanField(default=False),
        ),
    ]
