# Generated by Django 3.1 on 2020-08-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_subform_is_grid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkboxelement',
            name='value',
        ),
        migrations.CreateModel(
            name='IntegerField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_integerfield', to='core.field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloatField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('value', models.FloatField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_floatfield', to='core.field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=1024, null=True)),
                ('check_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.checkboxelement')),
            ],
        ),
    ]
