# Generated by Django 3.1 on 2020-08-16 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200816_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('value', models.CharField(blank=True, max_length=10240, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_textarea', to='core.field')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
