# Generated by Django 3.1 on 2020-08-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_textarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subform',
            name='is_grid',
        ),
        migrations.AddField(
            model_name='field',
            name='is_grid',
            field=models.BooleanField(default=False),
        ),
    ]
