# Generated by Django 3.1 on 2020-08-17 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200816_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxelement',
            name='answer_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.checkboxelement'),
        ),
        migrations.AddField(
            model_name='dateelement',
            name='answer_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.dateelement'),
        ),
        migrations.AddField(
            model_name='datetimeelement',
            name='answer_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.datetimeelement'),
        ),
        migrations.AddField(
            model_name='floatfield',
            name='answer_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.floatfield'),
        ),
        migrations.AddField(
            model_name='input',
            name='answer_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.input'),
        ),
        migrations.AddField(
            model_name='integerfield',
            name='answer_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.integerfield'),
        ),
        migrations.AddField(
            model_name='radioelement',
            name='answer_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.radioelement'),
        ),
        migrations.AddField(
            model_name='selectelement',
            name='answer_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.selectelement'),
        ),
        migrations.AddField(
            model_name='textarea',
            name='answer_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.textarea'),
        ),
        migrations.AddField(
            model_name='timeelement',
            name='answer_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.timeelement'),
        ),
    ]
