# Generated by Django 3.1 on 2020-08-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200817_1426'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Template',
        ),
    ]
