# Generated by Django 3.1 on 2020-08-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200817_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subform',
            old_name='form',
            new_name='template',
        ),
    ]
