# Generated by Django 3.1 on 2020-08-17 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200817_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkboxelement',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_checkboxelement', to='core.form'),
        ),
        migrations.AlterField(
            model_name='dateelement',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_dateelement', to='core.form'),
        ),
        migrations.AlterField(
            model_name='datetimeelement',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_datetimeelement', to='core.form'),
        ),
        migrations.AlterField(
            model_name='floatfield',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_floatfield', to='core.form'),
        ),
        migrations.AlterField(
            model_name='input',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_input', to='core.form'),
        ),
        migrations.AlterField(
            model_name='integerfield',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_integerfield', to='core.form'),
        ),
        migrations.AlterField(
            model_name='radioelement',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_radioelement', to='core.form'),
        ),
        migrations.AlterField(
            model_name='selectelement',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_selectelement', to='core.form'),
        ),
        migrations.AlterField(
            model_name='textarea',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_textarea', to='core.form'),
        ),
        migrations.AlterField(
            model_name='timeelement',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_timeelement', to='core.form'),
        ),
    ]
