# Generated by Django 3.1 on 2020-08-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200817_2051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkboxelement',
            unique_together={('answer_of', 'form')},
        ),
        migrations.AlterUniqueTogether(
            name='dateelement',
            unique_together={('answer_of', 'form')},
        ),
        migrations.AlterUniqueTogether(
            name='datetimeelement',
            unique_together={('answer_of', 'form')},
        ),
        migrations.AlterUniqueTogether(
            name='floatfield',
            unique_together={('answer_of', 'form')},
        ),
        migrations.AlterUniqueTogether(
            name='input',
            unique_together={('answer_of', 'form')},
        ),
        migrations.AlterUniqueTogether(
            name='integerfield',
            unique_together={('answer_of', 'form')},
        ),
        migrations.AlterUniqueTogether(
            name='radioelement',
            unique_together={('answer_of', 'form')},
        ),
        migrations.AlterUniqueTogether(
            name='selectelement',
            unique_together={('answer_of', 'form')},
        ),
        migrations.AlterUniqueTogether(
            name='textarea',
            unique_together={('answer_of', 'form')},
        ),
        migrations.AlterUniqueTogether(
            name='timeelement',
            unique_together={('answer_of', 'form')},
        ),
    ]
