# Generated by Django 3.1 on 2020-08-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_booleanfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleanfield',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
