# Generated by Django 3.1 on 2020-08-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200818_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BooleanField',
        ),
    ]
