# Generated by Django 3.1 on 2020-08-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_delete_booleanfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkboxelement',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements_checkboxelement', to='core.field'),
        ),
        migrations.AlterField(
            model_name='dateelement',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements_dateelement', to='core.field'),
        ),
        migrations.AlterField(
            model_name='datetimeelement',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements_datetimeelement', to='core.field'),
        ),
        migrations.AlterField(
            model_name='floatfield',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements_floatfield', to='core.field'),
        ),
        migrations.AlterField(
            model_name='input',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements_input', to='core.field'),
        ),
        migrations.AlterField(
            model_name='integerfield',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements_integerfield', to='core.field'),
        ),
        migrations.AlterField(
            model_name='radioelement',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements_radioelement', to='core.field'),
        ),
        migrations.AlterField(
            model_name='selectelement',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements_selectelement', to='core.field'),
        ),
        migrations.AlterField(
            model_name='textarea',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements_textarea', to='core.field'),
        ),
        migrations.AlterField(
            model_name='timeelement',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements_timeelement', to='core.field'),
        ),
    ]
