# Generated by Django 3.1 on 2020-08-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200819_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateelement',
            name='data',
            field=models.ManyToManyField(to='core.Data'),
        ),
        migrations.AddField(
            model_name='datetimeelement',
            name='data',
            field=models.ManyToManyField(to='core.Data'),
        ),
        migrations.AddField(
            model_name='floatfield',
            name='data',
            field=models.ManyToManyField(to='core.Data'),
        ),
        migrations.AddField(
            model_name='input',
            name='data',
            field=models.ManyToManyField(to='core.Data'),
        ),
        migrations.AddField(
            model_name='integerfield',
            name='data',
            field=models.ManyToManyField(to='core.Data'),
        ),
        migrations.AddField(
            model_name='textarea',
            name='data',
            field=models.ManyToManyField(to='core.Data'),
        ),
        migrations.AddField(
            model_name='timeelement',
            name='data',
            field=models.ManyToManyField(to='core.Data'),
        ),
    ]
