# Generated by Django 3.1 on 2020-08-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200819_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charfield',
            name='check_box',
        ),
        migrations.AddField(
            model_name='checkboxelement',
            name='values',
            field=models.ManyToManyField(to='core.CharField'),
        ),
        migrations.AlterField(
            model_name='checkboxelement',
            name='data',
            field=models.ManyToManyField(blank=True, to='core.Data'),
        ),
        migrations.AlterField(
            model_name='dateelement',
            name='data',
            field=models.ManyToManyField(blank=True, to='core.Data'),
        ),
        migrations.AlterField(
            model_name='datetimeelement',
            name='data',
            field=models.ManyToManyField(blank=True, to='core.Data'),
        ),
        migrations.AlterField(
            model_name='floatfield',
            name='data',
            field=models.ManyToManyField(blank=True, to='core.Data'),
        ),
        migrations.AlterField(
            model_name='input',
            name='data',
            field=models.ManyToManyField(blank=True, to='core.Data'),
        ),
        migrations.AlterField(
            model_name='integerfield',
            name='data',
            field=models.ManyToManyField(blank=True, to='core.Data'),
        ),
        migrations.AlterField(
            model_name='radioelement',
            name='data',
            field=models.ManyToManyField(blank=True, to='core.Data'),
        ),
        migrations.AlterField(
            model_name='selectelement',
            name='data',
            field=models.ManyToManyField(blank=True, to='core.Data'),
        ),
        migrations.AlterField(
            model_name='textarea',
            name='data',
            field=models.ManyToManyField(blank=True, to='core.Data'),
        ),
        migrations.AlterField(
            model_name='timeelement',
            name='data',
            field=models.ManyToManyField(blank=True, to='core.Data'),
        ),
    ]
