# Generated by Django 3.1 on 2020-08-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200819_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
