# Generated by Django 3.1 on 2020-08-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_form_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
