# Generated by Django 3.1 on 2020-08-29 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200828_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Boolean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('value', models.BooleanField(blank=True, null=True)),
                ('answer_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.boolean')),
                ('data', models.ManyToManyField(blank=True, to='core.Data')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements_boolean', to='core.field')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_boolean', to='core.form')),
            ],
            options={
                'abstract': False,
                'unique_together': {('answer_of', 'form')},
            },
        ),
    ]
