# Generated by Django 3.1 on 2020-09-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20200829_2306'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='form',
            unique_together={('template', 'description')},
        ),
    ]
