# Generated by Django 3.1 on 2020-09-14 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20200911_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('value', models.FileField(upload_to='')),
                ('answer_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.fileinput')),
                ('data', models.ManyToManyField(blank=True, to='core.Data')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements_fileinput', to='core.field')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_fileinput', to='core.form')),
            ],
            options={
                'abstract': False,
                'unique_together': {('answer_of', 'form')},
            },
        ),
    ]
