# Generated by Django 3.1 on 2020-09-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_fileinput'),
        ('core', '0043_auto_20200911_1800'),
    ]

    operations = [
    ]
