# Generated by Django 3.1 on 2020-09-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_merge_20200914_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinput',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
