# Generated by Django 3.1 on 2020-09-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_fileinput_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinput',
            name='value',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
