# Generated by Django 3.1 on 2020-12-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20200914_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='boolean',
            name='condition_element_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boolean',
            name='condition_element_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boolean',
            name='condition_element_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkboxelement',
            name='condition_element_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkboxelement',
            name='condition_element_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkboxelement',
            name='condition_element_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dateelement',
            name='condition_element_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dateelement',
            name='condition_element_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dateelement',
            name='condition_element_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datetimeelement',
            name='condition_element_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datetimeelement',
            name='condition_element_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datetimeelement',
            name='condition_element_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='condition_element_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='condition_element_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='condition_element_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fileinput',
            name='condition_element_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileinput',
            name='condition_element_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fileinput',
            name='condition_element_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='floatfield',
            name='condition_element_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floatfield',
            name='condition_element_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='floatfield',
            name='condition_element_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='condition_element_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='condition_element_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='condition_element_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integerfield',
            name='condition_element_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integerfield',
            name='condition_element_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integerfield',
            name='condition_element_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='radioelement',
            name='condition_element_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radioelement',
            name='condition_element_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='radioelement',
            name='condition_element_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='selectelement',
            name='condition_element_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectelement',
            name='condition_element_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='selectelement',
            name='condition_element_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subform',
            name='condition_element_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subform',
            name='condition_element_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subform',
            name='condition_element_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='textarea',
            name='condition_element_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textarea',
            name='condition_element_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='textarea',
            name='condition_element_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timeelement',
            name='condition_element_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeelement',
            name='condition_element_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timeelement',
            name='condition_element_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
