# Generated by Django 3.1 on 2021-01-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20201226_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_paginated',
            field=models.BooleanField(default=False),
        ),
    ]
