abstract_base_fields = ['pk', 'title', 'type', 'filters', 'order']
base_fields = abstract_base_fields + ['value', ]
base_field_fields_simple = ['pk', 'title', 'order', 'is_grid']
base_field_fields = base_field_fields_simple + ['elements', ]
abstract_element_fields = ['pk', 'title', 'type', 'order', 'field', 'data', 'disabled']
