abstract_base_fields = ['pk', 'title', 'type', 'filters', 'order']
base_fields = abstract_base_fields + ['value', ]
base_field_fields = ['pk', 'title', 'elements', 'order']
abstract_element_fields = ['pk', 'title', 'type', 'order', 'field']
base_element_fields = abstract_element_fields + ['value', ]
